version: '3.8'

services:
  backend:
    build:
      context: ./Go
    ports:
      - "8080:8080"
    env_file:
      - ./Go/.env  
    environment:
      DB_USER: root
      DB_PASSWORD: kenzi123
      DB_HOST: database
      DB_NAME: userdb
    depends_on:
      - database
    networks:
      - app_network
    command: /wait-for-it.sh database:3306 --timeout=30 -- ./main

  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    depends_on:
      - backend
    networks:
      - app_network

  database:
    build:
      context: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kenzi123
      MYSQL_DATABASE: userdb
    volumes:
      - db_data:/var/lib/mysql     # Ensure MySQL data is persisted
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure init.sql is loaded automatically      
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
